#!/usr/bin/env bash
# =============================================================================
# 02_kernel.sh — Kernel Parameter Hardening Module
# CIS Controls : 3.1, 3.2, 3.3 (Network parameters), 1.5 (ASLR)
# Description  : Applies security-focused sysctl parameters. All changes are
#                written to /etc/sysctl.d/99-hardening.conf for persistence
#                across reboots. Idempotent — safe to run multiple times.
# =============================================================================

SYSCTL_CONF="/etc/sysctl.d/99-hardening.conf"

apply() {
    if [[ "${APPLY}" == true ]]; then
        eval "$*"
    else
        log DRY "$*"
    fi
}

# ─── Sysctl parameters ────────────────────────────────────────────────────────
# Each line is "parameter=value". All are written to 99-hardening.conf and
# applied to the running kernel. Add or remove entries as needed.
SYSCTL_PARAMS=(
    # IP Spoofing & Source Routing (CIS 3.2.7, 3.1.1)
    # Prevents attackers from faking their IP address on the network
    "net.ipv4.conf.all.rp_filter=1"
    "net.ipv4.conf.default.rp_filter=1"
    "net.ipv4.conf.all.accept_source_route=0"
    "net.ipv4.conf.default.accept_source_route=0"
    "net.ipv6.conf.all.accept_source_route=0"

    # ICMP Redirects (CIS 3.2.2, 3.2.3, 3.1.2)
    # Prevents network redirect attacks that could silently reroute your traffic
    "net.ipv4.conf.all.accept_redirects=0"
    "net.ipv4.conf.default.accept_redirects=0"
    "net.ipv6.conf.all.accept_redirects=0"
    "net.ipv4.conf.all.secure_redirects=0"
    "net.ipv4.conf.default.secure_redirects=0"
    "net.ipv4.conf.all.send_redirects=0"
    "net.ipv4.conf.default.send_redirects=0"
    "net.ipv4.icmp_ignore_bogus_error_responses=1"

    # SYN Flood Protection (CIS 3.2.8)
    # Protects against a denial-of-service attack that floods TCP connections
    "net.ipv4.tcp_syncookies=1"
    "net.ipv4.tcp_syn_retries=2"
    "net.ipv4.tcp_synack_retries=2"

    # Broadcast & Logging (CIS 3.2.5, 3.2.4)
    "net.ipv4.icmp_echo_ignore_broadcasts=1"
    "net.ipv4.conf.all.log_martians=1"
    "net.ipv4.conf.default.log_martians=1"

    # IPv6 — disabled (CIS 3.3.3)
    # Not needed in this homelab setup
    "net.ipv6.conf.all.disable_ipv6=1"
    "net.ipv6.conf.default.disable_ipv6=1"

    # Memory & Exploit Mitigations (CIS 1.5.3)
    # Makes it harder for attackers to exploit memory vulnerabilities
    "kernel.randomize_va_space=2"
    "kernel.dmesg_restrict=1"
    "kernel.kptr_restrict=2"
    "kernel.yama.ptrace_scope=1"
    "fs.protected_hardlinks=1"
    "fs.protected_symlinks=1"
    "fs.suid_dumpable=0"
    "net.ipv4.tcp_rfc1337=1"
)

# ─── Apply sysctl params ──────────────────────────────────────────────────────
apply_sysctl_params() {
    log INFO "Checking sysctl hardening parameters..."

    for param in "${SYSCTL_PARAMS[@]}"; do
        local key
        local desired
        key=$(echo "${param}" | cut -d= -f1)
        desired=$(echo "${param}" | cut -d= -f2)
        local current
        current=$(sysctl -n "${key}" 2>/dev/null || echo "UNSET")

        if [[ "${current}" == "${desired}" ]]; then
            log OK "${key} already set to ${desired}"
        else
            log INFO "${key}: ${current} → ${desired}"
        fi
    done

    if [[ "${APPLY}" == true ]]; then
        # Write all params to the config file for persistence across reboots
        {
            echo "# Generated by linux-hardening/harden.sh"
            echo "# CIS Debian Linux Benchmark v2.0 — Kernel Parameters"
            echo ""
            for param in "${SYSCTL_PARAMS[@]}"; do
                echo "${param}"
            done
        } > "${SYSCTL_CONF}"
        log OK "Written: ${SYSCTL_CONF}"

        # Apply immediately (without needing a reboot)
        sysctl -p "${SYSCTL_CONF}" >> "${LOG_FILE}" 2>&1
        log OK "sysctl parameters applied to running kernel."
    else
        log DRY "Write ${SYSCTL_CONF} with ${#SYSCTL_PARAMS[@]} parameters"
        log DRY "sysctl -p ${SYSCTL_CONF}"
    fi
}

# ─── Core dumps ───────────────────────────────────────────────────────────────
disable_core_dumps() {
    # CIS 1.5.1 — Ensure core dumps are restricted
    log INFO "[CIS 1.5.1] Restricting core dumps..."

    local limits_conf="/etc/security/limits.d/99-coredump.conf"
    if [[ "${APPLY}" == true ]]; then
        echo "* hard core 0" > "${limits_conf}"
        log OK "Core dumps disabled via ${limits_conf}"
    else
        log DRY "echo '* hard core 0' > ${limits_conf}"
    fi
}

# ─── Module entry point ───────────────────────────────────────────────────────
run() {
    apply_sysctl_params
    disable_core_dumps
}
