#!/usr/bin/env bash
# =============================================================================
# 04_services.sh — Services & Attack Surface Reduction Module
# CIS Controls : 2.1 (unnecessary services), 2.2 (inetd), 1.1 (filesystems)
# Description  : Disables unnecessary services, removes risky packages, and
#                restricts filesystem mounting options to reduce attack surface.
# =============================================================================

apply() {
    if [[ "${APPLY}" == true ]]; then
        eval "$*"
    else
        log DRY "$*"
    fi
}

# ─── Unnecessary services to disable ─────────────────────────────────────────
# These are common services that are rarely needed in a homelab context.
# Review this list carefully — enable any you actually use before running.
SERVICES_TO_DISABLE=(
    "avahi-daemon"      # mDNS/zeroconf — network discovery, rarely needed
    "cups"              # Printing service
    "isc-dhcp-server"  # DHCP server — you're a client, not a server
    "slapd"             # LDAP server
    "nfs-server"        # NFS file sharing
    "rpcbind"           # RPC portmapper (required by NFS)
    "rsync"             # rsync daemon (not the CLI tool)
    "vsftpd"            # FTP server
    "apache2"           # Web server (use intentionally)
    "nginx"             # Web server (use intentionally)
    "smbd"              # Samba file sharing
    "snmpd"             # SNMP daemon
    "squid"             # Proxy server
    "talk"              # Legacy talk daemon
    "telnet"            # Cleartext remote shell — never acceptable
    "xinetd"            # Extended inetd
)

# ─── Packages to remove ───────────────────────────────────────────────────────
PACKAGES_TO_REMOVE=(
    "telnet"            # CIS 2.2.19 — Cleartext protocol, remove entirely
    "rsh-client"        # CIS 2.2.17 — Legacy remote shell
    "talk"              # CIS 2.2.18 — Legacy talk client
    "nis"               # CIS 2.2.16 — NIS (insecure, obsolete)
)

# ─── Disable unnecessary services ─────────────────────────────────────────────
disable_services() {
    log INFO "[CIS 2.1] Auditing and disabling unnecessary services..."

    for service in "${SERVICES_TO_DISABLE[@]}"; do
        local state
        state=$(systemctl is-enabled "${service}" 2>/dev/null || true)
        [[ -z "${state}" ]] && state="not-found"

        case "${state}" in
            enabled)
                log WARN "  ${service}: ENABLED → disabling"
                apply "systemctl disable --now ${service}"
                ;;
            disabled|masked)
                log OK "  ${service}: already disabled/masked"
                ;;
            not-found)
                log INFO "  ${service}: not found on this system"
                ;;
            *)
                log INFO "  ${service}: state=${state}"
                ;;
        esac
    done
}

# ─── Remove risky packages ────────────────────────────────────────────────────
remove_packages() {
    log INFO "[CIS 2.2] Removing unnecessary/risky packages..."

    for pkg in "${PACKAGES_TO_REMOVE[@]}"; do
        if dpkg-query -W -f='${Status}' "${pkg}" 2>/dev/null | grep -q "install ok installed"; then
            log WARN "  ${pkg}: installed → removing"
            apply "apt-get purge -y ${pkg} >> '${LOG_FILE}' 2>&1"
        else
            log OK "  ${pkg}: not installed"
        fi
    done

    # Clean up orphaned packages
    log INFO "Removing orphaned packages..."
    apply "apt-get autoremove -y >> '${LOG_FILE}' 2>&1"
}

# ─── Filesystem hardening ─────────────────────────────────────────────────────
harden_filesystems() {
    # CIS 1.1 — Disable mounting of uncommon/risky filesystems
    log INFO "[CIS 1.1] Disabling uncommon filesystem modules..."

    local modules_conf="/etc/modprobe.d/hardening-filesystems.conf"

    # Filesystems that should not be mountable on a hardened system
    declare -a FS_MODULES=(
        "cramfs|CIS 1.1.1.1|Rarely used compressed ROM filesystem"
        "freevxfs|CIS 1.1.1.2|Veritas filesystem — uncommon"
        "jffs2|CIS 1.1.1.3|Flash filesystem — not needed on x86"
        "hfs|CIS 1.1.1.4|Apple HFS"
        "hfsplus|CIS 1.1.1.5|Apple HFS+"
        "squashfs|CIS 1.1.1.6|Read-only compressed filesystem (snap dependency — check!)"
        "udf|CIS 1.1.1.7|Universal Disk Format (optical media)"
    )

    local conf_content="# CIS 1.1 — Disable uncommon filesystems\n# Generated by linux-hardening/harden.sh\n\n"

    for entry in "${FS_MODULES[@]}"; do
        IFS='|' read -r module cis desc <<< "${entry}"

        # Special warning for squashfs — snap uses it
        if [[ "${module}" == "squashfs" ]] && snap list &>/dev/null 2>&1; then
            log WARN "  squashfs: Snap packages detected — skipping squashfs disable to avoid breaking snap"
            continue
        fi

        conf_content+="# ${cis} — ${desc}\n"
        conf_content+="install ${module} /bin/true\n\n"

        local loaded
        loaded=$(lsmod | grep "^${module}" || echo "")
        if [[ -n "${loaded}" ]]; then
            log WARN "  ${module}: currently loaded — will be blocked on next boot"
        else
            log OK "  ${module}: not loaded"
        fi
    done

    if [[ "${APPLY}" == true ]]; then
        printf "%b" "${conf_content}" > "${modules_conf}"
        log OK "Filesystem module blocklist written: ${modules_conf}"
        log WARN "Module blocks take effect on next boot (or modprobe -r <module>)"
    else
        log DRY "Write ${modules_conf} with filesystem module blocklist"
    fi
}

# ─── Automatic updates ────────────────────────────────────────────────────────
configure_auto_updates() {
    # CIS 1.9 — Ensure updates and patches are applied
    log INFO "[CIS 1.9] Configuring unattended security updates..."

    if ! dpkg-query -W -f='${Status}' unattended-upgrades 2>/dev/null | grep -q "install ok installed"; then
        log INFO "Installing unattended-upgrades..."
        apply "apt-get install -y unattended-upgrades >> '${LOG_FILE}' 2>&1"
    else
        log OK "unattended-upgrades already installed."
    fi

    apply "systemctl enable unattended-upgrades"
    apply "systemctl start unattended-upgrades"
    log OK "Automatic security updates enabled."
}

# ─── SUID/SGID remediation ────────────────────────────────────────────────────
audit_suid() {
    log INFO "Auditing and remediating SUID/SGID binaries..."

    # Strip SUID/SGID from these — risky, legacy, or for services we've disabled
    declare -a SUID_STRIP=(
        "/usr/bin/pkexec"               # CVE-2021-4034 (PwnKit) — strip unconditionally
        "/usr/bin/rsh-redone-rlogin"    # Legacy cleartext remote login
        "/usr/bin/rsh-redone-rsh"       # Legacy cleartext remote shell
        "/usr/sbin/mount.nfs"           # NFS disabled — no need for unprivileged NFS mounts
        "/usr/sbin/mount.cifs"          # Samba disabled — no need for unprivileged CIFS mounts
        "/usr/sbin/pppd"                # PPP dial-up not used in homelab
        "/usr/bin/ntfs-3g"              # NTFS mounts should require root on a hardened system
    )

    # These are expected and required — do not touch
    declare -a SUID_EXPECTED=(
        "/usr/bin/crontab"
        "/usr/bin/passwd"
        "/usr/bin/newgrp"
        "/usr/bin/mount"
        "/usr/bin/umount"
        "/usr/bin/su"
        "/usr/bin/sudo"
        "/usr/bin/gpasswd"
        "/usr/bin/chage"
        "/usr/bin/chfn"
        "/usr/bin/chsh"
        "/usr/bin/expiry"
        "/usr/bin/plocate"
        "/usr/bin/dotlockfile"
        "/usr/bin/fusermount3"
        "/usr/bin/ssh-agent"
        "/usr/sbin/unix_chkpwd"
        "/usr/lib/dbus-1.0/dbus-daemon-launch-helper"
        "/usr/lib/openssh/ssh-keysign"
        "/usr/lib/xorg/Xorg.wrap"
        "/usr/lib/polkit-1/polkit-agent-helper-1"
        "/usr/lib/chromium/chrome-sandbox" # Chromium sandbox — without this --no-sandbox is required (worse)
        "/usr/lib/mysql/plugin/auth_pam_tool_dir/auth_pam_tool" # MariaDB PAM auth helper — needs SUID to verify passwords
    )

    # Strip the bad ones
    for target in "${SUID_STRIP[@]}"; do
        if [[ -f "${target}" ]]; then
            log WARN "  Stripping SUID/SGID: ${target}"
            apply "chmod a-s ${target}"
        fi
    done

    # Scan system and report anything not on the expected list
    log INFO "Scanning for unexpected SUID/SGID binaries..."
    local unexpected=0
    while IFS= read -r file; do
        local known=false
        for expected in "${SUID_EXPECTED[@]}"; do
            [[ "${file}" == "${expected}" ]] && known=true && break
        done
        # Also skip kismet capture binaries — Kali wireless tools, intentional
        [[ "${file}" == */kismet_cap_* ]] && known=true
        # Skip anything already in the strip list
        for strip in "${SUID_STRIP[@]}"; do
            [[ "${file}" == "${strip}" ]] && known=true && break
        done
        if [[ "${known}" == false ]]; then
            log WARN "  Unexpected SUID/SGID (review manually): ${file}"
            unexpected=1
        fi
    done < <(find / -xdev \( -perm -4000 -o -perm -2000 \) -type f 2>/dev/null || true)

    if [[ "${unexpected}" -eq 0 ]]; then
        log OK "No unexpected SUID/SGID binaries found."
    fi
}

# ─── Module entry point ───────────────────────────────────────────────────────
run() {
    disable_services
    remove_packages
    harden_filesystems
    configure_auto_updates
    audit_suid
}
