#!/usr/bin/env bash
# =============================================================================
# 05_audit.sh — Audit & Logging Module
# CIS Controls : 4.1 (auditd), 4.2 (syslog), 4.3 (logrotate)
# Description  : Configures auditd with CIS-aligned rules, ensures rsyslog
#                is running and configured, and verifies log rotation.
#                auditd rules are deployed from configs/auditd.rules.
# =============================================================================

apply() {
    if [[ "${APPLY}" == true ]]; then
        eval "$*"
    else
        log DRY "$*"
    fi
}

pkg_install() {
    local pkg="$1"
    if dpkg-query -W -f='${Status}' "${pkg}" 2>/dev/null | grep -q "install ok installed"; then
        log OK "${pkg} already installed."
    else
        log INFO "Installing ${pkg}..."
        apply "apt-get install -y ${pkg} >> '${LOG_FILE}' 2>&1"
    fi
}

# ─── auditd installation & config ─────────────────────────────────────────────
configure_auditd() {
    log INFO "[CIS 4.1] Configuring auditd..."

    pkg_install "auditd"
    pkg_install "audispd-plugins"

    # Deploy audit rules from configs/
    local rules_source="${SCRIPT_DIR}/configs/auditd.rules"
    local rules_dest="/etc/audit/rules.d/hardening.rules"

    if [[ -f "${rules_source}" ]]; then
        if [[ "${APPLY}" == true ]]; then
            cp "${rules_source}" "${rules_dest}"
            chmod 640 "${rules_dest}"
            log OK "auditd rules deployed to ${rules_dest}"
        else
            log DRY "cp ${rules_source} ${rules_dest}"
            log DRY "augenrules --load"
            # Show what rules would be applied
            log INFO "Rules to be deployed:"
            grep -v "^#\|^$" "${rules_source}" | while read -r rule; do
                log INFO "  ${rule}"
            done
        fi
    else
        log WARN "configs/auditd.rules not found — deploying inline CIS defaults..."
        write_default_audit_rules "${rules_dest}"
    fi

    # auditd daemon config — ensure logs don't get silently dropped
    local auditd_conf="/etc/audit/auditd.conf"
    if [[ -f "${auditd_conf}" ]]; then
        log INFO "Verifying auditd.conf key settings..."

        # CIS 4.1.2.2 — Ensure audit logs are not automatically deleted
        local current_action
        current_action=$(grep "^max_log_file_action" "${auditd_conf}" | awk '{print $3}')
        if [[ "${current_action}" != "keep_logs" ]]; then
            log WARN "max_log_file_action = ${current_action} → should be keep_logs"
            apply "sed -i 's/^max_log_file_action.*/max_log_file_action = keep_logs/' ${auditd_conf}"
        else
            log OK "max_log_file_action = keep_logs"
        fi

        # CIS 4.1.2.3 — Ensure system is disabled when audit logs are full
        local current_space
        current_space=$(grep "^space_left_action" "${auditd_conf}" | awk '{print $3}')
        if [[ "${current_space}" != "email" && "${current_space}" != "halt" ]]; then
            log WARN "space_left_action = ${current_space} → setting to email"
            apply "sed -i 's/^space_left_action.*/space_left_action = email/' ${auditd_conf}"
        else
            log OK "space_left_action = ${current_space}"
        fi
    fi

    apply "systemctl enable auditd"
    apply "systemctl restart auditd"

    # Load rules after auditd is running
    if [[ "${APPLY}" == true ]]; then
        augenrules --load >> "${LOG_FILE}" 2>&1 || log WARN "augenrules --load failed — rules will take effect on next reboot"
        systemctl enable audit-rules.service >> "${LOG_FILE}" 2>&1 && log OK "audit-rules.service enabled" || log WARN "Failed to enable audit-rules.service"
        log OK "auditd rules loaded."
    else
        log DRY "augenrules --load"
        log DRY "systemctl enable audit-rules.service"
    fi

    log OK "auditd enabled and started."
}

# ─── Inline default audit rules (fallback) ────────────────────────────────────
write_default_audit_rules() {
    local dest="$1"
    local content='# CIS 4.1 — Audit Rules (generated by linux-hardening)

# ── Audit log immutability (must be last rule) ────────────────────────────────
# -e 2 makes rules immutable until reboot (prevents tampering)

# ── Identity & authentication changes ────────────────────────────────────────
-w /etc/passwd -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/group -p wa -k identity
-w /etc/gshadow -p wa -k identity
-w /etc/security/opasswd -p wa -k identity

# ── Privilege escalation ──────────────────────────────────────────────────────
-w /bin/su -p x -k priv_esc
-w /usr/bin/sudo -p x -k priv_esc
-w /etc/sudoers -p wa -k scope
-w /etc/sudoers.d/ -p wa -k scope

# ── SSH configuration changes ─────────────────────────────────────────────────
-w /etc/ssh/sshd_config -p wa -k sshd

# ── Filesystem mounts ─────────────────────────────────────────────────────────
-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=unset -k mounts

# ── File deletion ─────────────────────────────────────────────────────────────
-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=unset -k delete

# ── Network configuration changes ─────────────────────────────────────────────
-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale
-w /etc/issue -p wa -k system-locale
-w /etc/issue.net -p wa -k system-locale
-w /etc/hosts -p wa -k system-locale
-w /etc/network/ -p wa -k system-locale

# ── Login events ──────────────────────────────────────────────────────────────
-w /var/log/lastlog -p wa -k logins
-w /var/run/faillock/ -p wa -k logins

# ── Session events ────────────────────────────────────────────────────────────
-w /var/run/utmp -p wa -k session
-w /var/log/wtmp -p wa -k session
-w /var/log/btmp -p wa -k session

# ── Kernel module loading ─────────────────────────────────────────────────────
-w /sbin/insmod -p x -k modules
-w /sbin/rmmod -p x -k modules
-w /sbin/modprobe -p x -k modules
-a always,exit -F arch=b64 -S init_module -S delete_module -k modules

# ── Immutable — must be last ──────────────────────────────────────────────────
-e 2'

    if [[ "${APPLY}" == true ]]; then
        echo "${content}" > "${dest}"
        chmod 640 "${dest}"
        log OK "Default audit rules written to ${dest}"
    else
        log DRY "Write default CIS audit rules to ${dest}"
    fi
}

# ─── rsyslog ──────────────────────────────────────────────────────────────────
configure_syslog() {
    # CIS 4.2.1 — Ensure rsyslog is installed and enabled
    log INFO "[CIS 4.2.1] Configuring rsyslog..."

    pkg_install "rsyslog"

    # On Kali, systemd-journald handles logging — rsyslog will fail to start if journald is active.
    # Only enable rsyslog if journald is NOT running.
    if systemctl is-active systemd-journald &>/dev/null; then
        log WARN "systemd-journald is active — skipping rsyslog start. Journald handles logging on this system."
    elif systemctl list-unit-files rsyslog.service 2>/dev/null | grep -q rsyslog; then
        apply "systemctl enable rsyslog"
        apply "systemctl start rsyslog"
        log OK "rsyslog enabled."
    else
        log WARN "rsyslog.service unit not found — skipping."
    fi

    # CIS 4.2.1.3 — Ensure rsyslog default file permissions are configured
    local rsyslog_conf="/etc/rsyslog.conf"
    if grep -q '^\$FileCreateMode' "${rsyslog_conf}" 2>/dev/null; then
        local mode
        mode=$(grep '^\$FileCreateMode' "${rsyslog_conf}" | awk '{print $2}')
        if [[ "${mode}" == "0640" ]]; then
            log OK "rsyslog FileCreateMode = 0640"
        else
            log WARN "rsyslog FileCreateMode = ${mode} → should be 0640"
            apply "sed -i 's/^\$FileCreateMode.*/$FileCreateMode 0640/' ${rsyslog_conf}"
        fi
    else
        log INFO "Setting rsyslog FileCreateMode to 0640..."
        apply "echo '\$FileCreateMode 0640' >> ${rsyslog_conf}"
    fi
}

# ─── Log file permissions ─────────────────────────────────────────────────────
audit_log_permissions() {
    # CIS 4.2.3 — Ensure log files are not accessible to unauthorised users
    log INFO "[CIS 4.2.3] Auditing /var/log permissions..."

    local found_bad=false
    for logfile in $(find /var/log -type f 2>/dev/null || true); do
        local perms
        perms=$(stat -c "%a" "${logfile}")
        # Log files should not be world-readable (others = 0)
        if [[ "${perms: -1}" != "0" ]]; then
            log WARN "  World-readable log: ${logfile} (${perms}) → fixing to 640"
            apply "chmod o-rwx '${logfile}'"
            found_bad=true
        fi
    done

    if [[ "${found_bad}" == false ]]; then
        log OK "All /var/log files have appropriate permissions."
    fi
}

# ─── logrotate ────────────────────────────────────────────────────────────────
check_logrotate() {
    # CIS 4.3 — Ensure logrotate is configured
    log INFO "[CIS 4.3] Checking logrotate..."

    if dpkg -l logrotate &>/dev/null; then
        log OK "logrotate is installed."
        if [[ -f "/etc/logrotate.conf" ]]; then
            local rotate_count
            rotate_count=$(grep "^rotate" /etc/logrotate.conf | awk '{print $2}')
            log INFO "  Log rotation: ${rotate_count:-not set} cycles"
        fi
    else
        log WARN "logrotate not installed — installing..."
        apply "apt-get install -y logrotate >> '${LOG_FILE}' 2>&1"
    fi
}

# ─── Module entry point ───────────────────────────────────────────────────────
run() {
    configure_auditd
    configure_syslog
    audit_log_permissions
    check_logrotate
}
